services:
  - type: web
    name: house-price-app
    env: python
    buildCommand: |
      pyenv install 3.10.13 -s
      pyenv global 3.10.13
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
